# Generated by Django 4.1.4 on 2022-12-17 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_marketitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
