# Generated by Django 4.1.4 on 2022-12-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0005_alter_marketitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitems',
            name='item_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='marketitems',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
