# Generated by Django 4.1.4 on 2022-12-07 23:03

from django.db import migrations
import tri.authh.managers


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', tri.authh.managers.AppUserManager()),
            ],
        ),
    ]
