# Generated by Django 4.1.4 on 2022-12-11 13:21

import django.core.validators
from django.db import migrations, models
import tri.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0002_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), tri.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), tri.common.validators.validate_only_letters]),
        ),
    ]
